## Assignment-3

### Task-1

#### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def div(a,b):
    try:
        i = int(a)/int(b)
        print('{}/{}={}'.format(a,b,i))
    except ZeroDivisionError:
        print('Cannot divide {} by {}'.format(a,b))
    except:
        print('Enter values correctly')

div(input('Enter numerator: '), input('Enter denominator: '))

Enter numerator: 5
Enter denominator: 0
Cannot divide 5 by 0


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [2]:
subject = ['Americans','Indians']
verb = ['play','watch']
object = ['Basketball', 'Cricket']

sentences = [(s+" "+v+" "+o+".") for s in subject for v in verb for o in object]

for sentence in sentences:
    print(sentence)

Americans play Basketball.
Americans play Cricket.
Americans watch Basketball.
Americans watch Cricket.
Indians play Basketball.
Indians play Cricket.
Indians watch Basketball.
Indians watch Cricket.


### Task 2

#### 1. Write a function so that the columns of the output matrix are powers of the input vector. <br><br>The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [3]:
import numpy as np

def my_vander(v, N=None, increasing=False):
    if N is None:
        N = len(v)
    if increasing:
        increasing=True
    list_arrays = [v**(N-i-1) for i in range(N)]
    if increasing:
        list_arrays.reverse()
    return np.column_stack(list_arrays)

In [4]:
print(my_vander(np.array([1,2,3,5])))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [5]:
print(my_vander(np.array([1,2,3,5]), increasing=False))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [6]:
print(my_vander(np.array([1,2,3,5]), increasing=True))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [7]:
print(my_vander(np.array([1,2,3,5]), N=2))

[[1 1]
 [2 1]
 [3 1]
 [5 1]]


In [8]:
print(my_vander(np.array([1,2,3,5]), N=5, increasing=True))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   5  25 125 625]]
